### ISSUE TITLE
Connexion ssh entre machines mongo

### ISSUE THREAD

**Issue by AerWyn81** [Tronix117/wik-devops-3tp#2]
Bonjour,

Nous avons un problème lorsque nous tentons de connecter nos machines grâce à notre playbook. Nous arrivons bien à communiquer en ssh entre nos machines avec echo : 

![image](https://user-images.githubusercontent.com/22222045/34327617-2892c98a-e8c9-11e7-8f81-14c5c8f41667.png)

Mais lorsque nous lançons nos machines avec le playbook : 
![image](https://user-images.githubusercontent.com/22222045/34327620-3dc157f4-e8c9-11e7-82af-a9dfa1dbb10b.png)

Notre playbook-provisionning : 
```
---

- name: Provisionning mongo's machines
  hosts: mongo
  become: true
  remote_user: root
  roles:
    - role: greendayonfire.mongodb

```
Et nous n'avons pour l'instant rien changé (sauf la clé rsa) dans default/main.yml (peut-être faut-il changer un paramètre ?).

Bonnes fêtes de fin d'année.

Cordialement,
MD & RV
