### ISSUE TITLE
a_homecolis-api_1 exited with code 0

### ISSUE THREAD

**Issue by aTewan** [Tronix117/wik-devops-3tp#7]
Bonjour,

Je ne comprends par pourquoi mais le conteneur de l'api s'éteint après avoir build mon docker-compose.

![screenshot at dec 30 15-19-01](https://user-images.githubusercontent.com/15360372/34454904-f9670328-ed74-11e7-9781-dd9c7860141d.png)

Je pensais que c'était lié au fait que MongoDB prenait trop de temps à se lancer mais même en rajoutant le code permettant de faire attendre l'API de l'issue #1 cela ne fonctionne pas.

Voici mon docker-compose.yml : 

```
version: '3'
services:
  homecolis-api:
   image: homecolis-api:latest
   environment:
   - NODE_ENV=development
   - PORT=8080
   - MONGO_HOST=mongo_db
   - MONGO_PORT=27017
   - MONGO_USER=user
   - MONGO_PASSWORD=password
   ports:
   - 80:8080
   links:
   - mongo_db:mongo_db
   depends_on:
   - mongo_db
   build: .
   
  mongo_db:
   image: mongo:latest
   environment:
   - MONGODB_ADMIN_USER=root
   - MONGODB_ADMIN_PASS=pass
   - MONGODB_APPLICATION_DATABASE=test
   - MONGODB_APPLICATION_USER=user
   - MONGODB_APPLICATION_PASS=password
   command:
    - '--auth'
   volumes:
   - ./data-db:/data/db
```
